CREATE TABLE Autor (
Id INT AUTO_INCREMENT,
Nome VARCHAR(255) NOT NULL,
data_nascimento DATE NOT NULL,
CPF CHAR (11) NOT NULL,
PRIMARY KEY(Id)
);

CREATE TABLE Categoria (
Id INT AUTO_INCREMENT,
Descricao VARCHAR(100) NOT NULL,
PRIMARY KEY (Id)
);

CREATE TABLE Livro (
Id INT AUTO_INCREMENT,
Id_Categoria INT NOT NULL,
Titulo VARCHAR(255) NOT NULL,
Editora VARCHAR(150) NOT NULL,
Ano YEAR NOT NULL,
Isbn VARCHAR(100) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (Id_Categoria) REFERENCES Categoria(Id)
);

CREATE TABLE Aluno(
Id INT AUTO_INCREMENT,
Nome VARCHAR(150),
RA INT,
Curso VARCHAR(150),
PRIMARY KEY (Id)
);

CREATE TABLE Usuario (
Id INT AUTO_INCREMENT,
Nome VARCHAR(150),
Email VARCHAR(100),
Senha VARCHAR(100),
PRIMARY KEY (Id)
);

CREATE TABLE Livro_Autor_Assoc (
Id_Livro INT NOT NULL,
Id_Autor INT NOT NULL,
FOREIGN KEY (Id_Livro) REFERENCES Livro (Id),
FOREIGN KEY (Id_autor) REFERENCES Autor (Id),
PRIMARY KEY (Id_Livro, Id_Autor)
);

CREATE TABLE Emprestimo (
Id INT AUTO_INCREMENT,
Data_Emprestimo DATE DEFAULT CURRENT_TIMESTAMP,
Data_Devolucao DATE,
Id_Usuario INT NOT NULL,
Id_Aluno INT NOT NULL,
Id_Livro INT NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY(Id_Usuario) REFERENCES Usuario (Id),
FOREIGN KEY(Id_Aluno) REFERENCES Aluno (Id),
FOREIGN KEY(Id_Livro) REFERENCES Livro (Id)
);